original_gadget/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('add', views.cart_add, name='cart_add'),
    path('add_cart_from_product/<int:product_id>', views.cart_add_from_product, name='cart_add_from_product'),
    path('remove_from_cart/<int:product_id>', views.remove_from_cart, name='remove_from_cart'),
    path('send_order/', views.send_order, name='send_order')
]

original_gadget/original_gadget/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls'))
]

original_gadget/shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('shop', views.index, name='shop'),
    path('product-details', views.index, name='product-details'),
    path('cart', views.cart, name='cart'),
    path('checkout', views.index, name='checkout'),
    path('shop/<str:category>', views.buy_category, name='buy_category'),
    path('shop/buy/<str:line>', views.buy_line, name='buy_line'),
    path('shop/buy-<str:category>/<str:product>', views.product_details, name='product_details'),
]

original_gadget/cart/models.py
from django.db import models

# Create your models here.

original_gadget/shop/models.py
from django.db import models

# Create your models here.

original_gadget/cart/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.http import JsonResponse
import requests

from .cart import Cart
import os
import sys
# Добавляем путь к папке, содержащей query_to_db.py
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))
# from query_to_db import *  # Импорт функции из query_to_db.py
import query_to_db


@require_POST
def cart_add(request):

    product_id = request.POST.get('product_id')  # берём данные из AJAX запроса

    cart = Cart(request)
    product_info = cart.add(product_id)
    cart.quantity = cart.__len__()

    category = product_info['category']
    slug = product_info['slug']

    # Возвращаем JSON с количеством товаров в корзине
    return JsonResponse({'cart_quantity': cart.__len__()})
    # return redirect('product_details', category=category, product=slug)


@require_POST
def cart_add_from_product(request, product_id):
    """
    Данная функция является временным форком cart_add и работает без ajax запроса. Просто обновляя страницу
    :param request:
    :param product_id:
    :return:
    """

    cart = Cart(request)
    product_info = cart.add(product_id)
    cart.quantity = cart.__len__()

    category = product_info['category']
    slug = product_info['slug']

    return redirect('product_details', category=category, product=slug)


# @require_POST
def remove_from_cart(request, product_id):
    cart = Cart(request)
    cart.remove(product_id)
    for item in cart:
        print(item)
    return redirect('cart')


@require_POST
def send_order(request):
    cart = Cart(request)
    text = request.POST.get('contact_info')  # получаем телефон или телегу которые указал пользователь
    text += '\n-----------\n'
    for item in cart:
        # print(item)
        text += f"**Товар:** {item['title']}\n**Цена:** {item['price']} ₽ \n----\n\n"

    token = '6888701276:AAHTtZfq0iKRl-mAbdGi7_LAbH4mc1EGOcs'

    url = f'https://api.telegram.org/bot{token}/sendMessage'

    chat_id = '480974372'

    data = {
        'chat_id': chat_id,
        'text': text,
        'parse_mode': 'Markdown',
    }
    requests.post(url, data)

    return redirect('cart')


# def cart_detail(request):  # находится в shop/views.py
#     cart = Cart(request)
#     return render(request, 'cart/detail.html', {'cart': cart})

original_gadget/shop/views.py
from django.shortcuts import render, HttpResponse
import sys
import os
from cart.cart import Cart  # из приложения cart Импортируем корзину

# Добавляем путь к папке, содержащей query_to_db.py
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))
import query_to_db


def index(request):
    context = {
        'current_category': 'HOME'
    }
    request.session.flush()
    return render(request, 'shop/index.html', context=context)


def buy_category(request, category):

    selected_characteristic = {}
    # формируем словарь выбранных характеристик для дальнейшей фильтрации списка товаров
    if request.method == 'POST':
        for characteristic in request.POST.keys():
            if characteristic != 'csrfmiddlewaretoken':
                selected_characteristic[characteristic] = request.POST.getlist(characteristic)
                # lines_and_products = query_to_db
        # input(selected_characteristic)  # словарь выбранных характеристик
    category = category.replace('-', ' ')
    lines_and_products = query_to_db.get_lines_and_products_in_category(category)

    # lines = []
    list_of_products = []
    list_product_ids = []

    for line, products in lines_and_products.items():
        # lines.append(line)
        for product in products:
            list_of_products.append(product)
            list_product_ids.append(product['id'])

    # формируем словарь значений характеристик товаров
    values_of_characteristics = query_to_db.get_value_of_characteristics_for_products(list_product_ids)
    lines = query_to_db.get_lines_in_category(category)
    context = {
        'current_category': category,
        'current_line': None,
        'lines': lines,
        'list_of_products': list_of_products,
        'values_of_characteristics': values_of_characteristics
    }

    return render(request, 'shop/shop.html', context)


def buy_line(request, line):

    if request.method == 'POST':  # выбрали необходимые характеристики
        selected_characteristic = {}
        # формируем словарь выбранных характеристик для дальнейшей фильтрации списка товаров
        for characteristic in request.POST.keys():
            if characteristic != 'csrfmiddlewaretoken':
                selected_characteristic[characteristic] = request.POST.getlist(characteristic)
    # end POST

    current_line = line.replace('-', ' ')  # надеюсь в названии линейки продукта никогда не встретится тире

    current_category, lines = query_to_db.get_category_and_lines_by_line(current_line)
    list_of_products = query_to_db.get_products_in_line(current_line)

    list_product_ids = [product['id'] for product in list_of_products]
    values_of_characteristics = query_to_db.get_value_of_characteristics_for_products(list_product_ids)
    context = {
        'current_category': current_category,
        'current_line': current_line,
        'lines': lines,
        'list_of_products': list_of_products,  # [{id:, title:, slug:, price: ... и т.д.}, ]
        'values_of_characteristics': values_of_characteristics,
    }

    # return HttpResponse(line + category + str(lines_and_products[' '.join(line.split('-'))]))
    return render(request, 'shop/shop.html', context)


def product_details(request, category, product):
    """
    :param request:
    :param category:
    :param product:
    :return: Получить название, описание, актуальную стоимость.
    """
    product_slug = product
    product = query_to_db.get_info_product(product_slug)  # product - product_slug
    cart = Cart(request)
    product_in_cart = cart.has_product(str(product['id']))
    print(category)
    context = {
        'product': product,  #
        'category': category.replace('-', ' ', category.count('-')),
        'product_in_cart': product_in_cart
    }
    return render(request, 'shop/product-details.html', context)


def cart(request):
    cart = Cart(request)
    total_price_of_cart = cart.get_total_price()
    context = {
        'cart': cart,
        'total_price_of_cart': total_price_of_cart
    }
    return render(request, 'shop/cart.html', context=context)

original_gadget/shop/templates/shop/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Original Gadget - Из Москвы с любовью | Cart</title>

    <!-- Favicon  -->
    <link rel="icon" href="img/core-img/favicon.ico" type="image/x-icon">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'shop/css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'shop/style.css' %}">

</head>

<body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="#" method="get">
                            <input type="search" name="search" id="search" placeholder="Type your keyword...">
                            <button type="submit"><img src="{% static 'img/core-img/search.png' %}" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="{% url 'index' %}">
                    <img src="{% static 'img/core-img/logo.png' %}" alt="Original Gadget logo">
                    <img src="{% static 'img/core-img/hat.png' %}" alt="Christmas Hat" class="mobile_hat">
                </a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        {% include 'header.html' %}

        <div class="cart-table-area section-padding-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        <div class="cart-title mt-50">
                            <h2>Shopping Cart</h2>
                        </div>

                        <div class="cart-table clearfix">
                            <table class="table table-responsive">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Command</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for product in cart %}
                                    <tr>
                                        <td class="cart_product_img">
                                            <a href="{% url 'product_details' category=product.category product=product.slug %}">
                                                {% if product.images %}
                                                    <img src="{% static product.path_to_img|add:product.images.0 %}" alt="{{ product.title }}">
                                                {% else %}
                                                    <img src="{% static 'img/product-img/no_image_1.jpg' %}" alt="нет картинки">
                                                {% endif %}
                                            </a>
                                        </td>
                                        <td class="cart_product_desc">
                                            <h5>{{ product.title }}</h5>
                                        </td>
                                        <td class="price">
                                            <span>{{ product.price }} ₽</span>
                                        </td>
                                        <td class="delete_button">
                                            <a href="{% url 'cart:remove_from_cart' product_id=product.id %}"><img src="{% static 'img/core-img/trash-can.png' %}"> Delete </a>
                                        </td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-12 col-lg-4">
                        <div class="cart-summary">
                            <h5>Cart Total</h5>
                            <ul class="summary-table">
                                <li><span>total:</span> <span>{{ total_price_of_cart }} ₽</span></li>
                            </ul>
                            <div class="cart-btn mt-100">
                                <form method="post" action="{% url 'cart:send_order' %}" onsubmit="return validateForm()">
                                    <input class="phone-or-telegram w-100" name='contact_info' placeholder="@telegram или телефон" autocomplete="off" id="telegram">
                                    {%csrf_token%}
                                    <button type="submit" name="addtocart" value="5" class="btn amado-btn w-100">
                                    Оформить заказ
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Main Content Wrapper End ##### -->

    {% include 'footer.html' %}

</body>

</html>
<!--Скрипт проверки заполнения формы telegram-->
<script>
    function validateForm() {
        var inputField = document.getElementById("telegram");
        var inputValue = inputField.value.trim();  // Удаляем пробелы в начале и конце

        if (inputValue === "") {
            alert("Пожалуйста, введите @telegram или телефон.");
            return false;  // Останавливаем отправку формы
        }

        return true;  // Разрешаем отправку формы
    }
</script>

original_gadget/shop/templates/shop/product-details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Купить {{product.full_name}} в магазине техники Apple Original Gadget - Из Москвы с любовью</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}" type="image/x-icon">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'shop/css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'shop/style.css' %}">

</head>

<body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="#" method="get">
                            <input type="search" name="search" id="search" placeholder="Type your keyword...">
                            <button type="submit"><img src="img/core-img/search.png" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="{% url 'index' %}">
                    <img src="{% static 'img/core-img/logo.png' %}" alt="Original Gadget logo">
                    <img src="{% static 'img/core-img/hat.png' %}" alt="Christmas Hat" class="mobile_hat">
                </a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        {% include 'header.html' %}

        <!-- Product Details Area Start -->
        <div class="single-product-area section-padding-100 clearfix">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb mt-50">
                                <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{% url 'buy_category' category=category|slugify %}">{{ category }}</a></li>
                                <li class="breadcrumb-item"><a href="{% url 'buy_line' line=product.line|slugify %}">{{ product.line }}</a></li>
                                <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'product_details' category=category|slugify product=product.slug %}">{{product.title}}</a></li>
                            </ol>
                        </nav>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-7">
                        <div class="single_product_thumb">
                            <div id="product_details_slider" class="carousel slide" data-ride="carousel">
                                {% if product.images %}
                                    <ol class="carousel-indicators">
                                        {% for image in product.images %}
                                        <li {% if forloop.first %}class="active"{% endif %} data-target="#product_details_slider" data-slide-to="{{ forloop.counter0 }}" style="background-image: url('{% static product.path_to_img|add:image %}');">{{ image }}</li>
                                        {% endfor %}
                                    </ol>
                                    <div class="carousel-inner">
                                        {% for image in product.images %}
                                        <div {% if forloop.first %}class="carousel-item active"{% endif %} class="carousel-item">
                                            <a class="gallery_img" href="{% static product.path_to_img|add:image %}">
                                                <img class="d-block w-100" src="{% static product.path_to_img|add:image %}" alt="{{ product.line }}">
                                            </a>
                                        </div>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    <ol class="carousel-indicators">
                                        <li class="active" data-target="#product_details_slider" data-slide-to="0" style="background-image: url('{% static 'img/product-img/no_image_1.jpg' %}');">image</li>
                                        <li data-target="#product_details_slider" data-slide-to="1" style="background-image: url('{% static 'img/product-img/no_image_2.jpg' %}');">image</li>
                                    </ol>
                                    <div class="carousel-inner">
                                        <div class="carousel-item active" class="carousel-item">
                                        <a class="gallery_img" href="{% static 'img/product-img/no_image_1.jpg' %}">
                                            <img class="d-block w-100" src="{% static 'img/product-img/no_image_1.jpg' %}" alt="no image">
                                        </a>
                                        </div>
                                        <div class="carousel-item" class="carousel-item">
                                            <a class="gallery_img" href="{% static 'img/product-img/no_image_2.jpg' %}">
                                                <img class="d-block w-100" src="{% static 'img/product-img/no_image_2.jpg' %}" alt="no image">
                                            </a>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-5">
                        <div class="single_product_desc">
                            <!-- Product Meta Data -->
                            <div class="product-meta-data">
                                <div class="line"></div>
                                <p class="product-price">₽{{product.price}}</p>
                                    <h6>{{product.full_name}}</h6>
                                <!-- Ratings & Review -->
                                <div class="ratings-review mb-15 d-flex align-items-center justify-content-between">
                                    <div class="ratings">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </div>
                                    <div class="review">
                                        <a href="https://market.yandex.ru/business--original-gadget/115386042" target="_blank">Мы на Yandex Market</a>
                                    </div>
                                </div>
                                <!-- Avaiable -->
                                <p class="avaibility"><i class="fa fa-circle"></i> In Stock</p>
                            </div>

                            <!-- Add to Cart Form -->
                            <form class="cart clearfix" method="{% if product_in_cart %}get{% else %}post{% endif %}" action="{% if product_in_cart %}{% url 'cart' %}{% else %}{% url 'cart:cart_add_from_product' product_id=product.id %}{% endif %}">
                                {% csrf_token %}
                                <button type="submit" name="addtocart" value="5" class="btn amado-btn">
                                    {% if product_in_cart %}
                                        Go to cart
                                    {% else %}
                                        Add to cart
                                    {% endif %}
                                </button>
                            </form>

                            <div class="short_overview my-5">
                                <p>{{product.description|safe}}</p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Product Details Area End -->
    </div>
    <!-- ##### Main Content Wrapper End ##### -->

    {% include 'footer.html' %}

</body>

</html>

original_gadget/shop/templates/shop/shop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Купить {{ current_category }} в магазине техники Apple OriginalGadget. Из Москвы с любовью </title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}" type="image/x-icon">

    <!-- Core Style CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'shop/css/core-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}">

    <!-- Подключение jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/2.1.3/jquery.scrollTo.min.js"></script>

</head>

<body>
    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="{% url 'index' %}">
                    <img src="{% static 'img/core-img/logo.png' %}" alt="Original Gadget logo">
                    <img src="{% static 'img/core-img/hat.png' %}" alt="Christmas Hat" class="mobile_hat">
                </a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>
        <a id="pop-up" href="{% url 'cart' %}">
            <img src="{% static 'img/core-img/shopping-cart.png' %}" alt="Перейти в корзину">
            <div id="cart-items-count">{{ cart|length }}</div>
        </a>
        {% include 'header.html' %}

        <!-- ##### Single Widget for mobile##### -->
        <div class="widget catagory mb-50 smart2">
            <!-- Widget Title -->
            <h6 class="widget-title mb-30">{{ current_category }}</h6>

            <!--  Lines of product  -->
            <div class="catagories-menu">
                <ul>
                    {% for line in lines %}
                        <li class="{% if line|lower == current_line %}active{% endif %}"><a href="{% url 'buy_line' line=line|slugify %}">{{ line }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        
        <div class="shop_sidebar_area">

            <!-- ##### Single Widget ##### -->
            <div class="widget catagory mb-50">
                <!-- Widget Title -->
                <h6 class="widget-title mb-30">{{ current_category }}</h6>

                <!--  Lines of product  -->
                <div class="catagories-menu">
                    <ul>
                        {% for line in lines %}
                            <li class="{% if line|lower == current_line %}active{% endif %}"><a href="{% url 'buy_line' line=line|slugify %}">{{ line }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

        <!--Characteristics-->

        <!--   Right column showcase with goods   -->
        <div class="amado_product_area section-padding-100">
            <div class="container-fluid">
                <!--Showing and sorting-->
                <div class="row">
                    {% for product in list_of_products %}
                        <!-- Single Product Area -->
                        <div class="col-12 col-sm-6 col-md-12 col-xl-6">
                            <div class="single-product-wrapper">
                                <!-- Product Image -->
                                <a href="{% url 'product_details' category=current_category|slugify product=product.slug %}">
                                    <div class="product-img">
                                    {% if product.images.0 and product.images.1 %}
                                        <img src="{% static product.path_to_img|add:product.images.1 %}" alt="{{ product.title }}">
                                        <!-- Hover Thumb -->
                                        <img class="hover-img" src="{% static product.path_to_img|add:product.images.0 %}" alt="{{ product.title }}">
                                    {% else %}
                                        <img src="{% static 'img/product-img/no_image_1.jpg' %}" alt="no image">
                                        <!-- Hover Thumb -->
                                        <img class="hover-img" src="{% static 'img/product-img/no_image_2.jpg' %}" alt="no image">
                                    {% endif %}
                                    </div>
                                </a>

                                <!-- Product Description -->
                                <div class="product-description d-flex align-items-center justify-content-between">
                                    <!-- Product Meta Data -->
                                    <div class="product-meta-data">
                                        <div class="line"></div>
                                        <p class="product-price">₽{{ product.price }}</p>
                                        <a href="{% url 'product_details' category=current_category|slugify product=product.slug %}">
                                            <h6>{{ product.title }}</h6>
                                        </a>
                                    </div>
                                    <!-- Ratings & Cart -->
                                    <div class="ratings-cart text-right">
                                        <div class="cart">
                                            <img class="add-to-cart-btn" data-product-id="{{ product.id }}" src="{% static 'img/core-img/cart.png' %}" alt="купить">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}


                </div>
                <div class="row">
                    <div class="col-12">
                        <!-- Pagination -->

                    </div>
                </div>
            </div>
        </div>
        <!--   end Right column showcase with goods   -->
    </div>
    <!-- ##### Main Content Wrapper End ##### -->
    
    {% include 'footer.html' %}
<script>
    // скрипт добавления товара без обновления страницы
    $(document).ready(function() {
    $('.add-to-cart-btn').click(function() {
        var productId = $(this).data('product-id');
        // AJAX запрос для добавления товара в корзину
        $.ajax({
            url: '{% url "cart:cart_add" %}',
            method: 'POST',
            data: {
                'product_id': productId,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response) {
                $('#cart-count').text('(' + response.cart_quantity + ')');
                $('#cart-items-count').text(response.cart_quantity);
                $('#pop-up').fadeIn();
            },
            error: function(response) {
                alert('Ошибка добавления товара в корзину.');
            }
        });
    });
});

</script>
</body>

</html>